/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

/* eslint-disable */
import * as React from "react";
import { getOverrideProps } from "./utils";
import { Flex, Icon, Text } from "@aws-amplify/ui-react";
import LargeButton from "./LargeButton";
export default function CalendarContent(props) {
  const { overrides, ...rest } = props;
  return (
    <Flex
      gap="32px"
      direction="column"
      width="1218px"
      height="855px"
      justifyContent="flex-start"
      alignItems="center"
      position="relative"
      padding="0px 0px 0px 0px"
      {...getOverrideProps(overrides, "CalendarContent")}
      {...rest}
    >
      <Flex
        gap="14px"
        direction="column"
        width="unset"
        height="748px"
        justifyContent="flex-start"
        alignItems="flex-start"
        shrink="0"
        alignSelf="stretch"
        position="relative"
        padding="0px 0px 0px 0px"
        {...getOverrideProps(overrides, "CalendarWrapper")}
      >
        <Flex
          gap="387px"
          direction="row"
          width="unset"
          height="unset"
          justifyContent="space-between"
          alignItems="center"
          shrink="0"
          alignSelf="stretch"
          position="relative"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "Header")}
        >
          <Text
            fontFamily="Inter"
            fontSize="24px"
            fontWeight="700"
            color="rgba(255,255,255,1)"
            lineHeight="40.20545196533203px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            shrink="0"
            position="relative"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="November"
            {...getOverrideProps(overrides, "November")}
          ></Text>
          <Text
            fontFamily="Inter"
            fontSize="32px"
            fontWeight="700"
            color="rgba(255,255,255,1)"
            lineHeight="53.607269287109375px"
            textAlign="center"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            shrink="0"
            position="relative"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="My Calendar"
            {...getOverrideProps(overrides, "My Calendar")}
          ></Text>
          <Flex
            gap="10px"
            direction="row"
            width="unset"
            height="unset"
            justifyContent="center"
            alignItems="center"
            shrink="0"
            position="relative"
            padding="0px 0px 0px 0px"
            {...getOverrideProps(overrides, "ViewFilter")}
          >
            <Text
              fontFamily="Inter"
              fontSize="16px"
              fontWeight="700"
              color="rgba(255,255,255,1)"
              lineHeight="26.803634643554688px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="unset"
              height="unset"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="Month View"
              {...getOverrideProps(overrides, "Month View")}
            ></Text>
            <Icon
              width="21px"
              height="11px"
              viewBox={{ minX: 0, minY: 0, width: 21, height: 11 }}
              paths={[
                {
                  d: "M10.5 11L9.77664 11.6905L10.5 12.4483L11.2234 11.6905L10.5 11ZM-0.723356 0.690476L9.77664 11.6905L11.2234 10.3095L0.723356 -0.690476L-0.723356 0.690476ZM11.2234 11.6905L21.7234 0.690476L20.2766 -0.690476L9.77664 10.3095L11.2234 11.6905Z",
                  stroke: "rgba(255,255,255,1)",
                  fillRule: "nonzero",
                  strokeWidth: 2,
                },
              ]}
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              shrink="0"
              position="relative"
              {...getOverrideProps(overrides, "Dropdown")}
            ></Icon>
          </Flex>
        </Flex>
        <Flex
          gap="0"
          direction="column"
          width="unset"
          height="unset"
          justifyContent="flex-start"
          alignItems="flex-start"
          overflow="hidden"
          grow="1"
          shrink="1"
          basis="0"
          alignSelf="stretch"
          position="relative"
          border="1px SOLID rgba(255,255,255,1)"
          borderRadius="12px"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "Calendar")}
        >
          <Flex
            gap="0"
            direction="row"
            width="unset"
            height="51px"
            justifyContent="flex-start"
            alignItems="flex-start"
            shrink="0"
            alignSelf="stretch"
            position="relative"
            padding="0px 0px 0px 0px"
            {...getOverrideProps(overrides, "WeekdayWrapper")}
          >
            <Flex
              gap="10px"
              direction="row"
              width="unset"
              height="unset"
              justifyContent="center"
              alignItems="flex-start"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863905")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="Sun"
                {...getOverrideProps(overrides, "Sun")}
              ></Text>
            </Flex>
            <Flex
              gap="10px"
              direction="row"
              width="unset"
              height="unset"
              justifyContent="center"
              alignItems="flex-start"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863907")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="Mon"
                {...getOverrideProps(overrides, "Mon")}
              ></Text>
            </Flex>
            <Flex
              gap="10px"
              direction="row"
              width="unset"
              height="unset"
              justifyContent="center"
              alignItems="flex-start"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863909")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="Tue"
                {...getOverrideProps(overrides, "Tue")}
              ></Text>
            </Flex>
            <Flex
              gap="10px"
              direction="row"
              width="unset"
              height="unset"
              justifyContent="center"
              alignItems="flex-start"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863911")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="Wed"
                {...getOverrideProps(overrides, "Wed")}
              ></Text>
            </Flex>
            <Flex
              gap="10px"
              direction="row"
              width="unset"
              height="unset"
              justifyContent="center"
              alignItems="flex-start"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863913")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="THU"
                {...getOverrideProps(overrides, "THU")}
              ></Text>
            </Flex>
            <Flex
              gap="10px"
              direction="row"
              width="unset"
              height="unset"
              justifyContent="center"
              alignItems="flex-start"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863915")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="Fri"
                {...getOverrideProps(overrides, "Fri")}
              ></Text>
            </Flex>
            <Flex
              gap="10px"
              direction="row"
              width="unset"
              height="unset"
              justifyContent="center"
              alignItems="flex-start"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863917")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="Sat"
                {...getOverrideProps(overrides, "Sat")}
              ></Text>
            </Flex>
          </Flex>
          <Flex
            gap="0"
            direction="row"
            width="unset"
            height="unset"
            justifyContent="flex-start"
            alignItems="flex-start"
            grow="1"
            shrink="1"
            basis="0"
            alignSelf="stretch"
            position="relative"
            padding="0px 0px 0px 0px"
            {...getOverrideProps(overrides, "DaysWrapper38863919")}
          >
            <Flex
              gap="10px"
              direction="row"
              width="unset"
              height="unset"
              justifyContent="center"
              alignItems="flex-start"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863920")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="30"
                {...getOverrideProps(overrides, "3038863921")}
              ></Text>
            </Flex>
            <Flex
              gap="10px"
              direction="row"
              width="unset"
              height="unset"
              justifyContent="center"
              alignItems="flex-start"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863922")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="31"
                {...getOverrideProps(overrides, "3138863923")}
              ></Text>
            </Flex>
            <Flex
              gap="10px"
              direction="row"
              width="unset"
              height="unset"
              justifyContent="center"
              alignItems="flex-start"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863924")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="1"
                {...getOverrideProps(overrides, "138863925")}
              ></Text>
            </Flex>
            <Flex
              gap="10px"
              direction="row"
              width="unset"
              height="unset"
              justifyContent="center"
              alignItems="flex-start"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863926")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="2"
                {...getOverrideProps(overrides, "238863927")}
              ></Text>
            </Flex>
            <Flex
              gap="10px"
              direction="row"
              width="unset"
              height="unset"
              justifyContent="center"
              alignItems="flex-start"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863928")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="3"
                {...getOverrideProps(overrides, "3")}
              ></Text>
            </Flex>
            <Flex
              gap="10px"
              direction="row"
              width="unset"
              height="unset"
              justifyContent="center"
              alignItems="flex-start"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863930")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="4"
                {...getOverrideProps(overrides, "4")}
              ></Text>
            </Flex>
            <Flex
              gap="10px"
              direction="row"
              width="unset"
              height="unset"
              justifyContent="center"
              alignItems="flex-start"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863932")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="5"
                {...getOverrideProps(overrides, "5")}
              ></Text>
            </Flex>
          </Flex>
          <Flex
            gap="0"
            direction="row"
            width="unset"
            height="unset"
            justifyContent="flex-start"
            alignItems="flex-start"
            grow="1"
            shrink="1"
            basis="0"
            alignSelf="stretch"
            position="relative"
            padding="0px 0px 0px 0px"
            {...getOverrideProps(overrides, "DaysWrapper38863934")}
          >
            <Flex
              gap="10px"
              direction="row"
              width="unset"
              height="unset"
              justifyContent="center"
              alignItems="flex-start"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863935")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="6"
                {...getOverrideProps(overrides, "6")}
              ></Text>
            </Flex>
            <Flex
              gap="10px"
              direction="row"
              width="unset"
              height="unset"
              justifyContent="center"
              alignItems="flex-start"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863937")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="7"
                {...getOverrideProps(overrides, "7")}
              ></Text>
            </Flex>
            <Flex
              gap="10px"
              direction="column"
              width="unset"
              height="unset"
              justifyContent="flex-start"
              alignItems="center"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863939")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="8"
                {...getOverrideProps(overrides, "8")}
              ></Text>
              <Text
                fontFamily="Work Sans"
                fontSize="16px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.03px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                alignSelf="stretch"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="4PM V2 Anime Watch Party"
                {...getOverrideProps(overrides, "4PM V2 Anime Watch Party")}
              ></Text>
            </Flex>
            <Flex
              gap="10px"
              direction="row"
              width="unset"
              height="unset"
              justifyContent="center"
              alignItems="flex-start"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863942")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="9"
                {...getOverrideProps(overrides, "9")}
              ></Text>
            </Flex>
            <Flex
              gap="10px"
              direction="row"
              width="unset"
              height="unset"
              justifyContent="center"
              alignItems="flex-start"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863944")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="10"
                {...getOverrideProps(overrides, "10")}
              ></Text>
            </Flex>
            <Flex
              gap="10px"
              direction="row"
              width="unset"
              height="unset"
              justifyContent="center"
              alignItems="flex-start"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863946")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="11"
                {...getOverrideProps(overrides, "11")}
              ></Text>
            </Flex>
            <Flex
              gap="10px"
              direction="row"
              width="unset"
              height="unset"
              justifyContent="center"
              alignItems="flex-start"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863948")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="12"
                {...getOverrideProps(overrides, "12")}
              ></Text>
            </Flex>
          </Flex>
          <Flex
            gap="0"
            direction="row"
            width="unset"
            height="unset"
            justifyContent="flex-start"
            alignItems="flex-start"
            grow="1"
            shrink="1"
            basis="0"
            alignSelf="stretch"
            position="relative"
            padding="0px 0px 0px 0px"
            {...getOverrideProps(overrides, "DaysWrapper38863950")}
          >
            <Flex
              gap="10px"
              direction="row"
              width="unset"
              height="unset"
              justifyContent="center"
              alignItems="flex-start"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863951")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="13"
                {...getOverrideProps(overrides, "13")}
              ></Text>
            </Flex>
            <Flex
              gap="10px"
              direction="row"
              width="unset"
              height="unset"
              justifyContent="center"
              alignItems="flex-start"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863953")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="14"
                {...getOverrideProps(overrides, "14")}
              ></Text>
            </Flex>
            <Flex
              gap="10px"
              direction="row"
              width="unset"
              height="unset"
              justifyContent="center"
              alignItems="flex-start"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863955")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="15"
                {...getOverrideProps(overrides, "15")}
              ></Text>
            </Flex>
            <Flex
              gap="10px"
              direction="row"
              width="unset"
              height="unset"
              justifyContent="center"
              alignItems="flex-start"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863957")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="16"
                {...getOverrideProps(overrides, "16")}
              ></Text>
            </Flex>
            <Flex
              gap="10px"
              direction="column"
              width="unset"
              height="unset"
              justifyContent="flex-start"
              alignItems="center"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863959")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="17"
                {...getOverrideProps(overrides, "17")}
              ></Text>
              <Text
                fontFamily="Work Sans"
                fontSize="16px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.03px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                alignSelf="stretch"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="6PM Beloved. Short Film Screening"
                {...getOverrideProps(
                  overrides,
                  "6PM Beloved. Short Film Screening"
                )}
              ></Text>
            </Flex>
            <Flex
              gap="10px"
              direction="row"
              width="unset"
              height="unset"
              justifyContent="center"
              alignItems="flex-start"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863962")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="18"
                {...getOverrideProps(overrides, "18")}
              ></Text>
            </Flex>
            <Flex
              gap="10px"
              direction="row"
              width="unset"
              height="unset"
              justifyContent="center"
              alignItems="flex-start"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863964")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="19"
                {...getOverrideProps(overrides, "19")}
              ></Text>
            </Flex>
          </Flex>
          <Flex
            gap="0"
            direction="row"
            width="unset"
            height="unset"
            justifyContent="flex-start"
            alignItems="flex-start"
            grow="1"
            shrink="1"
            basis="0"
            alignSelf="stretch"
            position="relative"
            padding="0px 0px 0px 0px"
            {...getOverrideProps(overrides, "DaysWrapper38863966")}
          >
            <Flex
              gap="10px"
              direction="row"
              width="unset"
              height="unset"
              justifyContent="center"
              alignItems="flex-start"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863967")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="20"
                {...getOverrideProps(overrides, "20")}
              ></Text>
            </Flex>
            <Flex
              gap="10px"
              direction="row"
              width="unset"
              height="unset"
              justifyContent="center"
              alignItems="flex-start"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863969")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="21"
                {...getOverrideProps(overrides, "21")}
              ></Text>
            </Flex>
            <Flex
              gap="10px"
              direction="row"
              width="unset"
              height="unset"
              justifyContent="center"
              alignItems="flex-start"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863971")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="22"
                {...getOverrideProps(overrides, "22")}
              ></Text>
            </Flex>
            <Flex
              gap="10px"
              direction="column"
              width="unset"
              height="unset"
              justifyContent="flex-start"
              alignItems="center"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863973")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="23"
                {...getOverrideProps(overrides, "23")}
              ></Text>
              <Text
                fontFamily="Work Sans"
                fontSize="16px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.03px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                alignSelf="stretch"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="4PM Ajaar S/S 24 Collection Exhibit"
                {...getOverrideProps(
                  overrides,
                  "4PM Ajaar S/S 24 Collection Exhibit"
                )}
              ></Text>
            </Flex>
            <Flex
              gap="10px"
              direction="row"
              width="unset"
              height="unset"
              justifyContent="center"
              alignItems="flex-start"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863976")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="24"
                {...getOverrideProps(overrides, "24")}
              ></Text>
            </Flex>
            <Flex
              gap="10px"
              direction="row"
              width="unset"
              height="unset"
              justifyContent="center"
              alignItems="flex-start"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863978")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="25"
                {...getOverrideProps(overrides, "25")}
              ></Text>
            </Flex>
            <Flex
              gap="10px"
              direction="row"
              width="unset"
              height="unset"
              justifyContent="center"
              alignItems="flex-start"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863980")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="26"
                {...getOverrideProps(overrides, "26")}
              ></Text>
            </Flex>
          </Flex>
          <Flex
            gap="0"
            direction="row"
            width="unset"
            height="unset"
            justifyContent="flex-start"
            alignItems="flex-start"
            grow="1"
            shrink="1"
            basis="0"
            alignSelf="stretch"
            position="relative"
            padding="0px 0px 0px 0px"
            {...getOverrideProps(overrides, "DaysWrapper38863982")}
          >
            <Flex
              gap="10px"
              direction="row"
              width="unset"
              height="unset"
              justifyContent="center"
              alignItems="flex-start"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863983")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="27"
                {...getOverrideProps(overrides, "27")}
              ></Text>
            </Flex>
            <Flex
              gap="10px"
              direction="row"
              width="unset"
              height="unset"
              justifyContent="center"
              alignItems="flex-start"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863985")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="28"
                {...getOverrideProps(overrides, "28")}
              ></Text>
            </Flex>
            <Flex
              gap="10px"
              direction="row"
              width="unset"
              height="unset"
              justifyContent="center"
              alignItems="flex-start"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863987")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="29"
                {...getOverrideProps(overrides, "29")}
              ></Text>
            </Flex>
            <Flex
              gap="10px"
              direction="row"
              width="unset"
              height="unset"
              justifyContent="center"
              alignItems="flex-start"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863989")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="30"
                {...getOverrideProps(overrides, "3038863990")}
              ></Text>
            </Flex>
            <Flex
              gap="10px"
              direction="row"
              width="unset"
              height="unset"
              justifyContent="center"
              alignItems="flex-start"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863991")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="31"
                {...getOverrideProps(overrides, "3138863992")}
              ></Text>
            </Flex>
            <Flex
              gap="10px"
              direction="row"
              width="unset"
              height="unset"
              justifyContent="center"
              alignItems="flex-start"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863993")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="1"
                {...getOverrideProps(overrides, "138863994")}
              ></Text>
            </Flex>
            <Flex
              gap="10px"
              direction="row"
              width="unset"
              height="unset"
              justifyContent="center"
              alignItems="flex-start"
              overflow="hidden"
              grow="1"
              shrink="1"
              basis="0"
              alignSelf="stretch"
              position="relative"
              border="1px SOLID rgba(255,255,255,1)"
              padding="9px 9px 9px 9px"
              {...getOverrideProps(overrides, "DayOfWeek38863995")}
            >
              <Text
                fontFamily="Work Sans"
                fontSize="24px"
                fontWeight="500"
                color="rgba(255,255,255,1)"
                lineHeight="24px"
                textAlign="left"
                display="block"
                direction="column"
                justifyContent="unset"
                letterSpacing="-0.11px"
                width="unset"
                height="unset"
                gap="unset"
                alignItems="unset"
                shrink="0"
                position="relative"
                padding="0px 0px 0px 0px"
                whiteSpace="pre-wrap"
                children="2"
                {...getOverrideProps(overrides, "238863996")}
              ></Text>
            </Flex>
          </Flex>
        </Flex>
      </Flex>
      <LargeButton
        display="flex"
        gap="24px"
        direction="row"
        width="325px"
        height="unset"
        justifyContent="center"
        alignItems="center"
        overflow="hidden"
        shrink="0"
        position="relative"
        borderRadius="36px"
        variation="Secondary"
        {...getOverrideProps(overrides, "LargeButton")}
      ></LargeButton>
    </Flex>
  );
}
