/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { FlexProps, IconProps, TextProps } from "@aws-amplify/ui-react";
import { LargeButtonProps } from "./LargeButton";
export declare type EscapeHatchProps = {
    [elementHierarchy: string]: Record<string, unknown>;
} | null;
export declare type VariantValues = {
    [key: string]: string;
};
export declare type Variant = {
    variantValues: VariantValues;
    overrides: EscapeHatchProps;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type CalendarContentOverridesProps = {
    "3"?: PrimitiveOverrideProps<TextProps>;
    "4"?: PrimitiveOverrideProps<TextProps>;
    "5"?: PrimitiveOverrideProps<TextProps>;
    "6"?: PrimitiveOverrideProps<TextProps>;
    "7"?: PrimitiveOverrideProps<TextProps>;
    "8"?: PrimitiveOverrideProps<TextProps>;
    "9"?: PrimitiveOverrideProps<TextProps>;
    "10"?: PrimitiveOverrideProps<TextProps>;
    "11"?: PrimitiveOverrideProps<TextProps>;
    "12"?: PrimitiveOverrideProps<TextProps>;
    "13"?: PrimitiveOverrideProps<TextProps>;
    "14"?: PrimitiveOverrideProps<TextProps>;
    "15"?: PrimitiveOverrideProps<TextProps>;
    "16"?: PrimitiveOverrideProps<TextProps>;
    "17"?: PrimitiveOverrideProps<TextProps>;
    "18"?: PrimitiveOverrideProps<TextProps>;
    "19"?: PrimitiveOverrideProps<TextProps>;
    "20"?: PrimitiveOverrideProps<TextProps>;
    "21"?: PrimitiveOverrideProps<TextProps>;
    "22"?: PrimitiveOverrideProps<TextProps>;
    "23"?: PrimitiveOverrideProps<TextProps>;
    "24"?: PrimitiveOverrideProps<TextProps>;
    "25"?: PrimitiveOverrideProps<TextProps>;
    "26"?: PrimitiveOverrideProps<TextProps>;
    "27"?: PrimitiveOverrideProps<TextProps>;
    "28"?: PrimitiveOverrideProps<TextProps>;
    "29"?: PrimitiveOverrideProps<TextProps>;
    "138863925"?: PrimitiveOverrideProps<TextProps>;
    "138863994"?: PrimitiveOverrideProps<TextProps>;
    "238863927"?: PrimitiveOverrideProps<TextProps>;
    "238863996"?: PrimitiveOverrideProps<TextProps>;
    "3038863921"?: PrimitiveOverrideProps<TextProps>;
    "3038863990"?: PrimitiveOverrideProps<TextProps>;
    "3138863923"?: PrimitiveOverrideProps<TextProps>;
    "3138863992"?: PrimitiveOverrideProps<TextProps>;
    CalendarContent?: PrimitiveOverrideProps<FlexProps>;
    CalendarWrapper?: PrimitiveOverrideProps<FlexProps>;
    Header?: PrimitiveOverrideProps<FlexProps>;
    November?: PrimitiveOverrideProps<TextProps>;
    "My Calendar"?: PrimitiveOverrideProps<TextProps>;
    ViewFilter?: PrimitiveOverrideProps<FlexProps>;
    "Month View"?: PrimitiveOverrideProps<TextProps>;
    Dropdown?: PrimitiveOverrideProps<IconProps>;
    Calendar?: PrimitiveOverrideProps<FlexProps>;
    WeekdayWrapper?: PrimitiveOverrideProps<FlexProps>;
    DayOfWeek38863905?: PrimitiveOverrideProps<FlexProps>;
    Sun?: PrimitiveOverrideProps<TextProps>;
    DayOfWeek38863907?: PrimitiveOverrideProps<FlexProps>;
    Mon?: PrimitiveOverrideProps<TextProps>;
    DayOfWeek38863909?: PrimitiveOverrideProps<FlexProps>;
    Tue?: PrimitiveOverrideProps<TextProps>;
    DayOfWeek38863911?: PrimitiveOverrideProps<FlexProps>;
    Wed?: PrimitiveOverrideProps<TextProps>;
    DayOfWeek38863913?: PrimitiveOverrideProps<FlexProps>;
    THU?: PrimitiveOverrideProps<TextProps>;
    DayOfWeek38863915?: PrimitiveOverrideProps<FlexProps>;
    Fri?: PrimitiveOverrideProps<TextProps>;
    DayOfWeek38863917?: PrimitiveOverrideProps<FlexProps>;
    Sat?: PrimitiveOverrideProps<TextProps>;
    DaysWrapper38863919?: PrimitiveOverrideProps<FlexProps>;
    DayOfWeek38863920?: PrimitiveOverrideProps<FlexProps>;
    DayOfWeek38863922?: PrimitiveOverrideProps<FlexProps>;
    DayOfWeek38863924?: PrimitiveOverrideProps<FlexProps>;
    DayOfWeek38863926?: PrimitiveOverrideProps<FlexProps>;
    DayOfWeek38863928?: PrimitiveOverrideProps<FlexProps>;
    DayOfWeek38863930?: PrimitiveOverrideProps<FlexProps>;
    DayOfWeek38863932?: PrimitiveOverrideProps<FlexProps>;
    DaysWrapper38863934?: PrimitiveOverrideProps<FlexProps>;
    DayOfWeek38863935?: PrimitiveOverrideProps<FlexProps>;
    DayOfWeek38863937?: PrimitiveOverrideProps<FlexProps>;
    DayOfWeek38863939?: PrimitiveOverrideProps<FlexProps>;
    "4PM V2 Anime Watch Party"?: PrimitiveOverrideProps<TextProps>;
    DayOfWeek38863942?: PrimitiveOverrideProps<FlexProps>;
    DayOfWeek38863944?: PrimitiveOverrideProps<FlexProps>;
    DayOfWeek38863946?: PrimitiveOverrideProps<FlexProps>;
    DayOfWeek38863948?: PrimitiveOverrideProps<FlexProps>;
    DaysWrapper38863950?: PrimitiveOverrideProps<FlexProps>;
    DayOfWeek38863951?: PrimitiveOverrideProps<FlexProps>;
    DayOfWeek38863953?: PrimitiveOverrideProps<FlexProps>;
    DayOfWeek38863955?: PrimitiveOverrideProps<FlexProps>;
    DayOfWeek38863957?: PrimitiveOverrideProps<FlexProps>;
    DayOfWeek38863959?: PrimitiveOverrideProps<FlexProps>;
    "6PM Beloved. Short Film Screening"?: PrimitiveOverrideProps<TextProps>;
    DayOfWeek38863962?: PrimitiveOverrideProps<FlexProps>;
    DayOfWeek38863964?: PrimitiveOverrideProps<FlexProps>;
    DaysWrapper38863966?: PrimitiveOverrideProps<FlexProps>;
    DayOfWeek38863967?: PrimitiveOverrideProps<FlexProps>;
    DayOfWeek38863969?: PrimitiveOverrideProps<FlexProps>;
    DayOfWeek38863971?: PrimitiveOverrideProps<FlexProps>;
    DayOfWeek38863973?: PrimitiveOverrideProps<FlexProps>;
    "4PM Ajaar S/S 24 Collection Exhibit"?: PrimitiveOverrideProps<TextProps>;
    DayOfWeek38863976?: PrimitiveOverrideProps<FlexProps>;
    DayOfWeek38863978?: PrimitiveOverrideProps<FlexProps>;
    DayOfWeek38863980?: PrimitiveOverrideProps<FlexProps>;
    DaysWrapper38863982?: PrimitiveOverrideProps<FlexProps>;
    DayOfWeek38863983?: PrimitiveOverrideProps<FlexProps>;
    DayOfWeek38863985?: PrimitiveOverrideProps<FlexProps>;
    DayOfWeek38863987?: PrimitiveOverrideProps<FlexProps>;
    DayOfWeek38863989?: PrimitiveOverrideProps<FlexProps>;
    DayOfWeek38863991?: PrimitiveOverrideProps<FlexProps>;
    DayOfWeek38863993?: PrimitiveOverrideProps<FlexProps>;
    DayOfWeek38863995?: PrimitiveOverrideProps<FlexProps>;
    LargeButton?: LargeButtonProps;
} & EscapeHatchProps;
export declare type CalendarContentProps = React.PropsWithChildren<Partial<FlexProps> & {
    overrides?: CalendarContentOverridesProps | undefined | null;
}>;
export default function CalendarContent(props: CalendarContentProps): React.ReactElement;
